fix = true

[lint]
select = [
    "E",
    "F",
    "W",   # flake8
    "I",   # isort
    "S",   # flake8-bandit
    "B",   #flake8-bugbear
    "N",   # pep8-naming
    "C90", # mccabe
    "RUF", # ruff
]
ignore = []

[lint.isort]
force-single-line = true

[analyze]
detect-string-imports = true

[format]
docstring-code-format = true
